# Generated by Django 2.1.2 on 2018-10-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_article_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_tag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
